package com.solona.domain;

public enum AccountStatus {
    PENDING_VERIFICATION,  //ACCOUNT IS CREATED BUT NOT YET VERIFIED
    ACTIVE,                //ACCOUNT IS ACTIVE IN GOOD STANDING
    SUSPENDED,             //ACCOUNT IS TEMPORARILY SUSPENDED, POSSIBLY DUR TO VIOLATIONS
    DEACTIVATED,           //ACCOUNT IS DEACTIVATED, USER MAY HAVE CHOSEN TO DEACTIVATE IT
    BANNED,                //ACCOUNT IS PERMANENTLY BANNED DUR TO SEVERE VIOLATIONS
    CLOSED                 //ACCOUNT IS PERMANENTLY CLOSED, POSSIBLY AT USER REQUEST
}
